feat(ci): implement CI pipeline for fork workflow

diff --git a/.github/workflows/pull-request.yaml b/.github/workflows/pull-request.yaml
--- a/.github/workflows/pull-request.yaml
+++ b/.github/workflows/pull-request.yaml
@@ -144,3 +144,64 @@ jobs:
           else
             echo "No changed CHANGELOGS, skip push"
           fi
+
+  publish-chart:
+    name: Publish Helm Chart
+    needs: [lint-test]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: azure/setup-helm@v4.3.1
+
+      - name: Checkout pull request branch
+        uses: actions/checkout@v5.0.0
+        with:
+          ref: ${{ github.head_ref }}
+          repository: ${{github.event.pull_request.head.repo.full_name}}
+          fetch-depth: 0
+
+      - name: Set up chart-testing-action
+        uses: helm/chart-testing-action@v2.7.0
+
+      - name: Get changed charts
+        id: list-changed
+        run: |
+          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
+          if [[ -n "$changed" ]]; then
+            echo "Changed charts:"
+            echo "$changed"
+            echo "changed=$changed" >> $GITHUB_OUTPUT
+          else
+            echo "No chart changes detected"
+          fi
+
+      - name: Publish Helm chart to ttl
+        id: upload
+        if: ${{ steps.list-changed.outputs.changed }}
+        run: |
+          CHANGED_CHARTS="${{ steps.list-changed.outputs.changed }}"
+
+          RELEASED_CHARTS=""
+          for chart_directory in ${CHANGED_CHARTS//,/ }; do
+            CHART_NAME=${chart_directory#charts/}
+
+            cd $chart_directory
+
+            CHART_VERSION='0.1.0-${{ github.run_number }}'
+            APP_VERSION='unstable-${GITHUB_SHA::7}'
+
+            helm dep update .
+            helm lint --strict .
+            helm package . --app-version=${APP_VERSION} --version=${CHART_VERSION}
+
+            # Push to GHCR
+            echo "Pushing Helm chart $CHART_NAME-$CHART_VERSION.tgz to oci://ttl.sh/${{ github.event.repository.name }}/helm"
+            if helm push ./$CHART_NAME-$CHART_VERSION.tgz oci://ttl.sh/${{ github.event.repository.name }}/helm; then
+              echo "Successfully released $CHART_NAME-$CHART_VERSION to ttl.sh"
+            else
+              echo "Failed to push $CHART_NAME-$CHART_VERSION to ttl.sh"
+              exit 1
+            fi
+
+            cd ${{ github.workspace }}
+          done
+          echo "released_charts=$RELEASED_CHARTS" >> "$GITHUB_OUTPUT"
